language: ruby
rvm:
  - 2.4.2
env:
  - DB=mysql
script:
  - RAILS_ENV=test bundle exec rake db:create db:migrate --trace
  - bundle exec rspec spec/
before_script:
  - cp config/database.travis.yml config/database.yml
  - mysql -e 'create database COURSE'
bundler_args: --binstubs=./bundler_stubs
